version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=confectionery_db
      - MYSQL_USER=confectionery
      - MYSQL_PASSWORD=secret
    volumes:
      - /var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
    - 'db'
    environment:
      - DATABASE_URL=mysql://confectionery:secret@db:3306/confectionery_db
    volumes:
      - .:/app

  streamlit:
    build: .
    command: streamlit run app/streamlit_app.py
    ports:
      - "8501:8501"
    depends_on:
      - web
    environment:
      - API_URL=http://web:8000
    volumes:
      - .:/appication-plugin=mysql_native_password
    